# Generated by Django 2.2.1 on 2019-05-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('style', models.CharField(blank=True, choices=[('Lager', 'Lager'), ('Ale', 'Ale')], max_length=112, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=10, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('long_description', models.TextField(blank=True, null=True)),
                ('mash_time', models.IntegerField(default='1', help_text='min.')),
                ('boil_time', models.IntegerField(default='1', help_text='min.')),
                ('original_gravity_sg', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('final_gravity_sg', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('original_gravity_plato', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_gravity_plato', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hop_type', models.CharField(blank=True, choices=[('Admiral', 'Admiral'), ('Ahtanum', 'Ahtanum'), ('Amarillo', 'Amarillo'), ('Apollo', 'Apollo'), ('Bramling Cross', 'Bramling Cross'), ('Brewers Gold', 'Brewers Gold'), ('Bullion', 'Bullion'), ('Cascade', 'Cascade'), ('Centennial', 'Centennial'), ('Challenger', 'Challenger'), ('Chinook', 'Chinook'), ('Citra', 'Citra'), ('Cluster', 'Cluster'), ('Columbus', 'Columbus'), ('Crystal', 'Crystal'), ('Eroica', 'Eroica'), ('First Gold', 'First Gold'), ('Feux-Coeur', 'Feux-Coeur'), ('Fuggle', 'Fuggle'), ('Galaxy', 'Galaxy'), ('Galena', 'Galena'), ('Glacier', 'Glacier'), ('Goldings', 'Goldings'), ('Green Bullet', 'Green Bullet'), ('Greenburg', 'Greenburg'), ('Hallertau', 'Hallertau'), ('Herald', 'Herald'), ('Herkules', 'Herkules'), ('Hersbrucker', 'Hersbrucker'), ('Horizon', 'Horizon'), ('Liberty', 'Liberty'), ('Lublin', 'Lublin'), ('Magnum', 'Magnum'), ('Merkur', 'Merkur'), ('Millennium', 'Millennium'), ('Motueka', 'Motueka'), ('Mosaic', 'Mosaic'), ('Mount Hood', 'Mount Hood'), ('Mount Rainier', 'Mount Rainier'), ('Nelson Sauvin', 'Nelson Sauvin'), ('Newport', 'Newport'), ('Northdown', 'Northdown'), ('Northern Brewer', 'Northern Brewer'), ('Nugget', 'Nugget'), ('Opal', 'Opal'), ('Pacifica', 'Pacifica'), ('Pacific Gem', 'Pacific Gem'), ('Pacific Jade', 'Pacific Jade'), ('Palisade', 'Palisade'), ('Perle', 'Perle'), ('Phoenix', 'Phoenix'), ('Pilgrim', 'Pilgrim'), ('Pilot', 'Pilot'), ('Pioneer', 'Pioneer'), ('Polnischer', 'Polnischer'), ('Pride of Ringwood', 'Pride of Ringwood'), ('Progress', 'Progress'), ('Riwaka', 'Riwaka'), ('Saaz', 'Saaz'), ('Saaz Late', 'Saaz Late'), ('Bor', 'Bor'), ('Premiant', 'Premiant'), ('Rubin', 'Rubin'), ('Agnus', 'Agnus'), ('Vital', 'Vital'), ('Sladek', 'Sladek'), ('Kazbek', 'Kazbek'), ('Bohemie', 'Bohemie'), ('Harmonie', 'Harmonie'), ('San Juan Ruby Red', 'San Juan Ruby Red'), ('Santiam', 'Santiam'), ('Saphir', 'Saphir'), ('Satus', 'Satus'), ('Select', 'Select'), ('Simcoe', 'Simcoe'), ('Smaragd', 'Smaragd'), ('Sorachi Ace', 'Sorachi Ace'), ('Southern Cross', 'Southern Cross'), ('Spalt', 'Spalt'), ('Sterling', 'Sterling'), ('Strisselspalt', 'Strisselspalt'), ('Styrian Aurora', 'Styrian Aurora'), ('Styrian Bobek', 'Styrian Bobek'), ('Styrian Goldings', 'Styrian Goldings'), ('Styrian Celeia', 'Styrian Celeia'), ('Summit', 'Summit'), ('Tardif de Bourgogne', 'Tardif de Bourgogne'), ('Target', 'Target'), ('Taurus', 'Taurus'), ('Tettnang', 'Tettnang'), ('Tomahawk', 'Tomahawk'), ('Tomyski', 'Tomyski'), ('Tradition', 'Tradition'), ('Ultra', 'Ultra'), ('Vanguard', 'Vanguard'), ('Waimea', 'Waimea'), ('Warrior', 'Warrior'), ('Whitbread Golding Variety', 'Whitbread Golding Variety'), ('Willamette', 'Willamette'), ('Zeus', 'Zeus')], max_length=50, null=True)),
                ('hop_quantity', models.IntegerField(default='1', help_text='gr.')),
                ('added_at', models.IntegerField(blank=True, help_text='kaçinci dakikada eklendi?', null=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='crudapp.Recipe')),
            ],
        ),
    ]
